//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKO.PingPing.Mobile.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EKO.PingPing.Mobile.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden....
        /// </summary>
        internal static string Generic_Loading {
            get {
                return ResourceManager.GetString("Generic.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginPage_Header {
            get {
                return ResourceManager.GetString("LoginPage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        internal static string LoginPage_InputLabel_Password {
            get {
                return ResourceManager.GetString("LoginPage.InputLabel.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        internal static string LoginPage_InputLabel_Username {
            get {
                return ResourceManager.GetString("LoginPage.InputLabel.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginPage_Submit {
            get {
                return ResourceManager.GetString("LoginPage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string ProfilePage_Details_Email {
            get {
                return ResourceManager.GetString("ProfilePage.Details.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam:.
        /// </summary>
        internal static string ProfilePage_Details_Name {
            get {
                return ResourceManager.GetString("ProfilePage.Details.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam:.
        /// </summary>
        internal static string ProfilePage_Details_Username {
            get {
                return ResourceManager.GetString("ProfilePage.Details.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string ProfilePage_Header {
            get {
                return ResourceManager.GetString("ProfilePage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string ProfilePage_LogOut {
            get {
                return ResourceManager.GetString("ProfilePage.LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk Logins.
        /// </summary>
        internal static string ProfilePage_More_SeeLogins {
            get {
                return ResourceManager.GetString("ProfilePage.More.SeeLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recente Transacties.
        /// </summary>
        internal static string PursePage_Subheader_RecentTransactions {
            get {
                return ResourceManager.GetString("PursePage.Subheader.RecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw saldo is:.
        /// </summary>
        internal static string PursePage_Subheader_YourBalance {
            get {
                return ResourceManager.GetString("PursePage.Subheader.YourBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessie is succesvol uitgelogd..
        /// </summary>
        internal static string Sessions_Logout_Success_Message {
            get {
                return ResourceManager.GetString("Sessions.Logout.Success.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes.
        /// </summary>
        internal static string Sessions_Logout_Success_Title {
            get {
                return ResourceManager.GetString("Sessions.Logout.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere Logins:.
        /// </summary>
        internal static string SessionsPage_Header {
            get {
                return ResourceManager.GetString("SessionsPage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De huidige login wordt niet getoont, u kan uitloggen via de knop op de profiel pagina..
        /// </summary>
        internal static string SessionsPage_Subheader {
            get {
                return ResourceManager.GetString("SessionsPage.Subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankopen.
        /// </summary>
        internal static string Shell_Tabs_History {
            get {
                return ResourceManager.GetString("Shell.Tabs.History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht.
        /// </summary>
        internal static string Shell_Tabs_Main {
            get {
                return ResourceManager.GetString("Shell.Tabs.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel.
        /// </summary>
        internal static string Shell_Tabs_Profile {
            get {
                return ResourceManager.GetString("Shell.Tabs.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistieken.
        /// </summary>
        internal static string Shell_Tabs_Stats {
            get {
                return ResourceManager.GetString("Shell.Tabs.Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw Statistieken.
        /// </summary>
        internal static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze maand uitgegeven:.
        /// </summary>
        internal static string Statistics_TotalMonthlySpent {
            get {
                return ResourceManager.GetString("Statistics.TotalMonthlySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorige maand uitgegeven:.
        /// </summary>
        internal static string Statistics_TotalPreviousMonthlySpent {
            get {
                return ResourceManager.GetString("Statistics.TotalPreviousMonthlySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal uitgegeven bedrag:.
        /// </summary>
        internal static string Statistics_TotalSpent {
            get {
                return ResourceManager.GetString("Statistics.TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit jaar uitgegeven:.
        /// </summary>
        internal static string Statistics_TotalYearlySpent {
            get {
                return ResourceManager.GetString("Statistics.TotalYearlySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw eerdere Transacties:.
        /// </summary>
        internal static string TransactionHistoryPage_Header {
            get {
                return ResourceManager.GetString("TransactionHistoryPage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo, {0}!.
        /// </summary>
        internal static string UserGreetingConverter_GreetingFormat {
            get {
                return ResourceManager.GetString("UserGreetingConverter.GreetingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er ging iets mis bij het uitloggen..
        /// </summary>
        internal static string ValdiationError_UserLogoutFailed_Message {
            get {
                return ResourceManager.GetString("ValdiationError.UserLogoutFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout.
        /// </summary>
        internal static string ValidationError_Generic_Error {
            get {
                return ResourceManager.GetString("ValidationError.Generic.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer uw gegevens en probeer het opnieuw..
        /// </summary>
        internal static string ValidationError_UserLoginFailed_Message {
            get {
                return ResourceManager.GetString("ValidationError.UserLoginFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Mislukt.
        /// </summary>
        internal static string ValidationError_UserLoginFailed_Title {
            get {
                return ResourceManager.GetString("ValidationError.UserLoginFailed.Title", resourceCulture);
            }
        }
    }
}
